name: spotify
channels:
  - conda-forge
dependencies:
  - async-timeout=5.0.1=pyhcf101f3_2
  - backports.zstd=1.3.0=py314h680f03e_0
  - beautifulsoup4=4.14.3=pyha770c72_0
  - brotli-python=1.2.0=py314he701e3d_1
  - bzip2=1.0.8=h0ad9c76_8
  - ca-certificates=2026.1.4=h4c7d964_0
  - certifi=2026.1.4=pyhd8ed1ab_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - coverage=7.13.3=py314h2359020_0
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - idna=3.11=pyhd8ed1ab_0
  - iniconfig=2.3.0=pyhd8ed1ab_0
  - invoke=2.2.1=pyhd8ed1ab_0
  - libexpat=2.7.3=hac47afa_0
  - libffi=3.5.2=h3d046cb_0
  - liblzma=5.8.2=hfd05255_0
  - libmpdec=4.0.0=hfd05255_1
  - libsqlite=3.51.2=hf5d6505_0
  - libzlib=1.3.1=h2466b09_2
  - openssl=3.6.1=hf411b9b_1
  - packaging=26.0=pyhcf101f3_0
  - pip=26.0.1=pyh145f28c_0
  - pluggy=1.6.0=pyhf9edf01_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pysocks=1.7.1=pyh09c184e_7
  - pytest=9.0.2=pyhcf101f3_0
  - pytest-cov=7.0.0=pyhcf101f3_1
  - python=3.14.3=h4b44e0e_100_cp314
  - python_abi=3.14=8_cp314
  - redis-py=7.1.0=pyhd8ed1ab_0
  - requests=2.32.5=pyhcf101f3_1
  - ruff=0.15.0=h213852a_0
  - six=1.17.0=pyhe01879c_1
  - soupsieve=2.8.3=pyhd8ed1ab_0
  - spotipy=2.25.2=pyhd8ed1ab_0
  - tk=8.6.13=h6ed50ae_3
  - tomli=2.4.0=pyhcf101f3_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025c=hc9c84f9_1
  - ucrt=10.0.26100.0=h57928b3_0
  - urllib3=2.6.3=pyhd8ed1ab_0
  - vc=14.3=h41ae7f8_34
  - vc14_runtime=14.44.35208=h818238b_34
  - vcomp14=14.44.35208=h818238b_34
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - zstd=1.5.7=h534d264_6

prefix: "C:\\Users\\forbe\\.local\\share\\mamba\\envs\\spotify"
